version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium_backup_app
    restart: always
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - ROLE_ID=${ROLE_ID}
      - SERVER_ID=${SERVER_ID}
      - GAME=${GAME}
      - DO_BACKUP=${DO_BACKUP}
      - BACKUP_TIMER=${BACKUP_TIMER}
      - CONFIG_TIMER_MULTIPLE_PLAYER=${CONFIG_TIMER_MULTIPLE_PLAYER}
      - CONFIG_TIMER_SINGLE_PLAYER=${CONFIG_TIMER_SINGLE_PLAYER}
      - CONFIG_TIMER_NO_PLAYER=${CONFIG_TIMER_NO_PLAYER}
      - QUERY_URL=${QUERY_URL}
      - BACKUP_URL=${BACKUP_URL}
      - BASE_URL=${BASE_URL}
      - SELENIUM_URL=selenium-hub
      - BROWSER=firefox  # Use 'chrome' or 'edge' if needed
    volumes:
      - /dev/shm:/dev/shm  # To enhance performance for headless browsers
    depends_on:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
    shm_size: '2g'

volumes:
  browser_data:
